<?php /** @var Alyona\PostEAV\Block\Widget\Tags $block */?>
<div class="tag_widget columns">
    <h2>Category List</h2>
    <?php
    $test = $this->getLayout()->createBlock("Alyona\PostEAV\Block\Widget\CategoryList")->setData("categories", $block->returnOptions());
    foreach ($test->getData('categories') as $item) { ?>
        <a href="https://<?php echo $_SERVER['HTTP_HOST']?>/blog/<?php echo str_replace(" ", "-", strtolower($item['label'])); ?>"><?php echo $item['label']; ?></a>
    <?php }?>
</div>
