<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var Magento\Framework\View\Element\Template $block */
$categories = $block->getCategories();
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation">
    <ul id="menu"
        data-mage-init='{"menu":{"responsive":true, "expanded":true, "delay": 200, "position":{"my":"left top","at":"left+10 top+30"}}}'>
        <li class="level0 level-top ui-menu-item">
            <a class="level-top ui-corner-all" id="ui-id-8" tabindex="-1" role="menuitem"
               href="https://<?php echo $_SERVER['HTTP_HOST'] ?>/blog">
                All posts
            </a>
        </li>
        <li class="level0 level-top parent ui-menu-item">Categories &#9660
            <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all">
                <?php foreach ($categories->getItems() as $category): ?>
                    <li class="ui-menu-item">
                        <a href="https://<?php echo $_SERVER['HTTP_HOST'] ?>/blog/<?php echo $category->getName(); ?>">
                            <?php echo $category->getName(); ?>
                        </a>
                    </li>
                <?php endforeach; ?>

            </ul>
        </li>
    </ul>

</nav>

