<?php
/** @var Magento\Framework\View\Element\Template $block */
$categories = $block->getCategories();
?>

<nav class="navigation" data-action="navigation">
    <ul id="menu"
        data-mage-init='{"menu":{"responsive":true, "expanded":true, "delay": 200, "position":{"my":"left top","at":"left+10 top+30"}}}'>
        <li class="level0 level-top ui-menu-item">
            <a class="level-top ui-corner-all" id="ui-id-8" tabindex="-1" role="menuitem"
               href="https://<?php echo $_SERVER['HTTP_HOST'] ?>/blog">
                All posts
            </a>
        </li>
        <li class="level0 level-top parent ui-menu-item">Categories &#9658
        </li>

        <?php foreach ($categories->getItems() as $category): ?>
            <li class="level0 level-top parent ui-menu-item">
                <a class="level-top"
                    href="https://<?php echo $_SERVER['HTTP_HOST'] ?>/blog/<?php echo $category->getName(); ?>">
                    <?php echo $category->getName(); ?>
                </a>
            </li>
        <?php endforeach; ?>

    </ul>

</nav>

