<?php /** @var Magento\Framework\View\Element\Template $block */
if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>
<?php $productColl = $block->getProductCollection(); ?>
<?php if ($productColl && count($productColl->getData()) > 0): ?>
    <ul class="blog-container">
    <?php foreach ($productColl as $product): ?>
        <li class="post-container">
            <div class="post-container__content">
                <a href="https://<?php echo $_SERVER['HTTP_HOST']?>/blog/post/index/<?php echo $product->getUrlKey();?>"><h2><?php echo $product->getTitle();?></h2></a>
                <div class="post-meta">
                    <div class="column1">
                        Categories:
                        <?php foreach ($block->getCategories($product->getId()) as $category): ?>
                        <a href="https://<?php echo $_SERVER['HTTP_HOST']?>/blog/index/index/category/<?php echo $category;?>"><span class="rect" ><?php echo $category;?></span></a>
                        <?php endforeach; ?>
                        <br/>
                        tags:
                        <?php foreach ($block->getTags($product->getId()) as $tag): ?>
                        <span class="rect"><?php echo $tag; ?></span>
                        <?php endforeach; ?>
                    </div>
                    <div class="column2"> <?php echo $product->getUpdatedAt();?></div>
                </div>
                <p><?php echo $block->getPreview($product->getId());?></p>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('You have no any records in your custom collection.'); ?></span></div>
<?php endif ?>
