<?php
/** @var Magento\Framework\View\Element\Template $block */
$post = $block->getPostInfo();
?>
<li class="post-container">
    <div class="post-container__content">
        <h2><?php echo $post->getTitle();?></h2>
        <div class="post-meta">
            <div class="column1">
                Categories:
                <a href="blog/category/index"><span class="rect"><?php echo $post->getCategoryId() ?></span></a>
                <br/>
                tags:
                <span class="rect"><?php echo $post->getTags(); ?></span>
            </div>
            <div class="column2"> <?php echo $post->getUpdatedAt(); ?></div>
        </div>
        <p><?php echo $post->getPostContent(); ?></p>
    </div>
</li>
